### ISSUE TITLE
nz.co.breakpoint.jmeter.modifiers.SecurityPart cannot be cast to org.apache.jmeter.testelement.property.JMeterProperty

### ISSUE THREAD

**Issue by sandervanwanrooy** [tilln/jmeter-wssecurity#12]
JMeter 3.2 r17900748 & WS Security for SOAP (jmeter-wssecurity-1.5.jar)
Reproduced in clean JMeter 3.2 r17900748 with jmeter-plugins-manager-0.20.jar and jmeter-wssecurity-1.5.jar

Could not reproduce in 3.3

Steps to reproduce:
1. Add Thread Group
2. Add HTTP Request with SOAP Message Signer
3. Add another HTTP Request with SOAP Message Signer. Add 1 row in Parts to Sign with all three fields filled
4. Save the script --> Error occurs

Extra note: Error does not occur when both SOAP Message Signer don't have parts to sign, both have parts to sign or #2 and #3 are switched (so first has part to sign and second does not)

Error:
 2018-03-29 10:08:47,302 ERROR o.a.j.g.a.ActionRouter: Error processing org.apache.jmeter.gui.action.Save@9573b3b
java.lang.ClassCastException: nz.co.breakpoint.jmeter.modifiers.SecurityPart cannot be cast to org.apache.jmeter.testelement.property.JMeterProperty
	at org.apache.jmeter.testelement.property.PropertyIteratorImpl.next(PropertyIteratorImpl.java:41) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.testelement.property.PropertyIteratorImpl.next(PropertyIteratorImpl.java:24) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.save.converters.MultiPropertyConverter.marshal(MultiPropertyConverter.java:57) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66) ~[xstream-1.4.9.jar:1.4.9]
	at org.apache.jmeter.save.converters.TestElementConverter.marshal(TestElementConverter.java:74) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66) ~[xstream-1.4.9.jar:1.4.9]
	at org.apache.jmeter.save.converters.HashTreeConverter.marshal(HashTreeConverter.java:53) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66) ~[xstream-1.4.9.jar:1.4.9]
	at org.apache.jmeter.save.converters.HashTreeConverter.marshal(HashTreeConverter.java:54) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66) ~[xstream-1.4.9.jar:1.4.9]
	at org.apache.jmeter.save.converters.HashTreeConverter.marshal(HashTreeConverter.java:54) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66) ~[xstream-1.4.9.jar:1.4.9]
	at org.apache.jmeter.save.converters.HashTreeConverter.marshal(HashTreeConverter.java:54) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88) ~[xstream-1.4.9.jar:1.4.9]
	at org.apache.jmeter.save.ScriptWrapperConverter.marshal(ScriptWrapperConverter.java:79) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1067) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1056) ~[xstream-1.4.9.jar:1.4.9]
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1029) ~[xstream-1.4.9.jar:1.4.9]
	at org.apache.jmeter.save.SaveService.saveTree(SaveService.java:303) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.action.Save.doAction(Save.java:223) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:74) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:59) ~[ApacheJMeter_core.jar:3.2 r1790748]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_144]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_144]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_144]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_144]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_144]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_144]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_144]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_144]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_144]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_144]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_144]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_144]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_144]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_144]

**Comment by anthonygauthier** [comment]
Hi there,

What are the elements you're trying to sign exactly? What's the text?

Thanks,

**Comment by sandervanwanrooy** [comment]
Hi Anthony,
In the steps to reproduce I tried to find out the simpliest way to get the error.

With the Blazemeter blog I was trying to find out how send a signed message to an endpoint, so I made a script and each request I was enhancing the request with extra elements.
So in one of the requests I added the SOAP Message Signer with a keystore and certificate, but I did not fill in the Parts to Sign. This gave me a Not Authorized reply. In the next request I added the parts which needed to be signed (Timestamp, Body, To, MessageID and Action), all with the namespaces and Encode = 'Content'. 
I then got the saving error and in the jmx-file I noticed the last part was <collectionProp name="partsToSecure" (the rest of the jmx could not be saved). Opening this partial script gave an error too.

So I took a new script trying to find out which request was causing the actual problem and how it could simply be reproduced.

**Comment by sandervanwanrooy** [comment]
![soapmessagesigner-partstosign](https://user-images.githubusercontent.com/37895432/38085166-e2d7f1a0-334f-11e8-8967-1c461dee31bc.png)

**Comment by anthonygauthier** [comment]
Hi @sandervanwanrooy,

I personally wasn't able to reproduce your error with a fresh JMeter 3.2 installation (with only the WS Security plugin installed). My guess is that maybe you have another plugin that's conflicting with 

```java
com.thoughtworks.xstream.core
```
Are you able to reproduce your issue with a fresh installation of JMeter 3.2 with only the PluginsManager and the WS Security Plugin installed?

Thanks!

**Comment by sandervanwanrooy** [comment]
Hi, 
I just tried on a newly installed Windows 10 PC.
Downloaded apache-jmeter-3.2.zip from https://archive.apache.org/dist/jmeter/binaries/
Downloaded jmeter-plugins-manager-0.20.jar from https://jmeter-plugins.org/wiki/PluginsManager/
Started JMeter and downloaded WS Security for SOAP with the PluginsManager
JMeter restarted after install.

Created following testplan. All elements are default, except for bottom SOAP Message Signer. I added 1 part to sign. Saving the testplan didn't give an error this time, but when I closed and reopened the script I got the same error. I also attached the jmx below.
![3 2_soap message signer](https://user-images.githubusercontent.com/37895432/38091921-26ddf446-3367-11e8-8913-98163561e878.png)

[SOAP Message Signer.zip](https://github.com/tilln/jmeter-wssecurity/files/1860334/SOAP.Message.Signer.zip)

**Comment by anthonygauthier** [comment]
Hi,

So I found out why JMeter is throwing the error. Look at your test's JMX file, it should basically be ending like this : 

```xml
<stringProp name="HTTPSampler.method">GET</stringProp>
          <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
          <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
          <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
          <stringProp name="HTTPSampler.embedded_url_re"></stringProp>
          <stringProp name="HTTPSampler.connect_timeout"></stringProp>
          <stringProp name="HTTPSampler.response_timeout"></stringProp>
        </HTTPSamplerProxy>
        <hashTree>
          <nz.co.breakpoint.jmeter.modifiers.WSSSignaturePreProcessor guiclass="TestBeanGUI" testclass="nz.co.breakpoint.jmeter.modifiers.WSSSignaturePreProcessor" testname="SOAP Message Signer" enabled="true">
            <stringProp name="certAlias"></stringProp>
            <stringProp name="certPassword"></stringProp>
            <stringProp name="digestAlgorithm">http://www.w3.org/2000/09/xmldsig#sha1</stringProp>
            <stringProp name="keyIdentifier">Binary Security Token</stringProp>
            <stringProp name="keystoreFile"></stringProp>
            <stringProp name="keystorePassword"></stringProp>
            <stringProp name="signatureAlgorithm">http://www.w3.org/2000/09/xmldsig#rsa-sha1</stringProp>
            <stringProp name="signatureCanonicalization">http://www.w3.org/2001/10/xml-exc-c14n#</stringProp>
            <boolProp name="useSingleCertificate">false</boolProp>
            <collectionProp name="partsToSecure"
```

The ```collectionProp``` tag never ends. I'm taking a look at the code as we speak to try and pinpoint where this is occuring. @tilln will most likely be able to help much faster, but I'll try my best to help out :) !

Thanks,

**Comment by anthonygauthier** [comment]
@sandervanwanrooy 

Pretty sure I found the issue! It is indeed related to ```com.thoughtworks.xstream```in JMeter 3.2, the reason why you're unable to reproduce the error in JMeter 3.3+ is because they updated the ```xstream```JAR to version 1.4.10 from 1.4.9. There must be some sort of defect in 1.4.9 which is causing the issue here.

Solution would be to update your JMeter client, is it a requirement for you to use JMeter 3.2? Using JMeter 3.3 or even JMeter 4.0 would most likely be better, lots has happened since 3.2!

Cheers,

**Comment by tilln** [comment]
Thanks @sandervanwanrooy for reporting and @delirius325 for analysing.
I agree that it looks like an xstream related issue.
As I have just started a 2 month holiday without access to a dev machine so won't be able to properly look into this for a while.
What I'd suggest in the meantime is either upgrading JMeter or try if swapping just the xstream jar file (1.4.9 to 1.4.10) in the JMeter 3.2 installation fixes this.
On first glance there is nothing obvious here
http://x-stream.github.io/changes.html
that relates to this issue nor should break compatibility in JMeter 3.2

**Comment by sandervanwanrooy** [comment]
Hi,
Thanks for your help. We are planning an upgrade to 4.0, so that would fix the problem for us.
The collectionProp tag never ending was caused by the jar. The endtag is there in the uploaded jmx-file.

**Comment by tilln** [comment]
Hi @sandervanwanrooy 
Is this still an issue or can this be closed?

**Comment by Highlander4h** [comment]
Not longer an issue for me. We have migrated to 4.0. Thanks
