### ISSUE TITLE
try to sign with jks file (with private key inside

### ISSUE THREAD

**Issue by QuentinDezetter** [tilln/jmeter-wssecurity#30]
https://github.com/tilln/jmeter-wssecurity/blob/4e045d61665e30ca587555401355f7b0a95d7971/src/main/java/nz/co/breakpoint/jmeter/modifiers/CryptoTestElement.java#L42

```2019-10-02 09:31:05,390 DEBUG n.c.b.j.m.WSSSignaturePreProcessor: Initializing WSSecSignature
2019-10-02 09:31:05,390 DEBUG o.a.w.c.u.Loader: Trying to find [C:/WIN-B3GPCUINS7V.jks] using org.apache.jmeter.DynamicClassLoader@5ef04b5 class loader.
2019-10-02 09:31:05,390 DEBUG o.a.w.c.u.Loader: Trying to find [C:/WIN-B3GPCUINS7V.jks] using org.apache.jmeter.DynamicClassLoader@5ef04b5 class loader.
2019-10-02 09:31:05,390 DEBUG o.a.w.c.u.Loader: Trying to find [C:/WIN-B3GPCUINS7V.jks] using ClassLoader.getSystemResource().
2019-10-02 09:31:05,391 DEBUG o.a.w.c.c.Merlin: The KeyStore C:/WIN-B3GPCUINS7V.jks of type JCEKS has been loaded
2019-10-02 09:31:05,392 ERROR n.c.b.j.m.AbstractWSSecurityPreProcessor: Processing failed! 
java.lang.ClassCastException: sun.security.rsa.RSAPrivateCrtKeyImpl cannot be cast to javax.crypto.SecretKey
	at nz.co.breakpoint.jmeter.modifiers.CryptoTestElement.getSecretKey(CryptoTestElement.java:43) ~[jmeter-wssecurity-1.7.jar:?]
	at nz.co.breakpoint.jmeter.modifiers.WSSSignaturePreProcessor.build(WSSSignaturePreProcessor.java:93) ~[jmeter-wssecurity-1.7.jar:?]
	at nz.co.breakpoint.jmeter.modifiers.AbstractWSSecurityPreProcessor.process(AbstractWSSecurityPreProcessor.java:63) [jmeter-wssecurity-1.7.jar:?]
	at org.apache.jmeter.threads.JMeterThread.runPreProcessors(JMeterThread.java:935) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:537) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253) [ApacheJMeter_core.jar:5.1.1 r1855137]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]```

**Comment by QuentinDezetter** [comment]
parameters  on capture
<a href="https://www.casimages.com/i/191002095648539230.png.html" title="Image 12" target="_blank"><img src="https://nsa40.casimages.com/img/2019/10/02/mini_191002095648539230.png" border="0" alt="Image 12" /></a>

**Comment by tilln** [comment]
Hi @QuentinDezetter 

Looks like you are trying to generate a symmetric signature (hmac-sha1) with an asymmetric key: the alias B3GPCUINS7V references an RSA private key.
For a symmetric signature you need a [Secret Key](https://docs.oracle.com/javase/8/docs/api/javax/crypto/SecretKey.html).
